### ISSUE TITLE
support for newer versions of pip (8.1.2)?

### ISSUE THREAD

**Issue by beaugunderson** [tweekmonster/moult#1]
I get this when I try to run `moult` within a virtual environment with pip 8.1.2:

```
Activating /Users/beau/.envs/open-humans
Traceback (most recent call last):
  File "/usr/local/bin/moult", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/moult/__init__.py", line 37, in main
    from moult.program import run
  File "/usr/local/lib/python2.7/site-packages/moult/program.py", line 5, in <module>
    from . import color, printer, filesystem_scanner, utils, log
  File "/usr/local/lib/python2.7/site-packages/moult/printer.py", line 7, in <module>
    from .utils import running_under_virtualenv
  File "/usr/local/lib/python2.7/site-packages/moult/utils.py", line 6, in <module>
    from .pip_importer import *
  File "/usr/local/lib/python2.7/site-packages/moult/pip_importer.py", line 19, in <module>
    raise MoultCommandError('Could not import pip functions')
moult.exceptions.MoultCommandError: Could not import pip functions
```

**Comment by tweekmonster** [comment]
A year later, I issue #1.  Hah!  Anyways, I guess the hardcoded ignore list was removed.  I'll update after I fix up the repo.  The branches are a bit of a mess.

**Comment by beaugunderson** [comment]
thanks for the quick fix; excited to try this out :)

---
